#
# The worlds that we want to have access to freebuild functionality
#
FreebuildWorldNames: [W_SurvivalFreebuild]

#
# The fly speed for freebuilders that can fly
#
FlySpeed: 0.3

#
# The mandatory cooldown time between calling /freebuild on and /freebuild off
#
CoolDownTime: 30m

eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1

commands:
  #
  # This command is dispatched when a player starts to fly in freebuild mode.
  # Parameters: <FlySpeed> (%.2f), <player name> (%s)
  #
  SetSpeed: speed fly %.2f %s
  
  #
  # This command is dispatched when a player tries to fly when not supposed to.
  # Parameters: -
  #
  StopFly: fly

messages:

  #
  # This message is displayed when someone tries to use freebuild outside the allowed worlds (see FreebuildWorldNames)
  # It has no parameters.
  #
  MustBeInFreebuildWord: You can only switch between survival and freebuild in the SurvivalFreebuild world.

  #
  # This message is displayed when someone switches to fast between on and off
  # Parameters: <minutes left> (%d), <seconds left> (%d)
  #
  WaitForCoolDown: The remaining cool down period for switching Freebuild mode is %d minutes and %d seconds.

  #
  # The player tried to activate freebuild mode, but it already was active.
  # Parameters: NONE
  #
  AlreadyOn_0: Freebuild mode is already active.

  #
  # The player tried to deactivate freebuild mode, but it already was deactivated.
  # Parameters: NONE
  #
  AlreadyOff_0: Survival mode is already active (freebuild is OFF).

  #
  # The freebuild mode has been successfully activated
  # Parameters: NONE
  #
  Activated_0: Freebuild mode is now active.

  #
  # The freebuild mode has been successfully deactivated
  # Parameters: NONE
  #
  Deactivated_0: Survival mode is now active (freebuild is OFF).
